language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

matrix:
  include:
    - php: 7.4
      env: composer_extra="--prefer-lowest --prefer-stable"
    - name: Highest stable version dependencies
      php: 8.0
      env: composer_extra="--prefer-stable"
  fast_finish: true

install:
  - composer $composer_extra update

script:
  - ./vendor/bin/phpunit
